apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-web-service"
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30088
  selector:
    release: {{ .Release.Name }}
    app: "web-{{ .Release.Name }}"

